name: active_storage
description: Send files to a Rails Active Storage backend using direct upload
version: 0.2.0
homepage: https://www.algonauti.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  test: any
